"""Regression suite for `benchmarks/adversarial/` — the evasion-focused
benchmark corpus generated by `scripts/build_adversarial_corpus.py`. Unlike
`test_labs.py` (which needs an external DVAS checkout and skips without
one), this corpus lives inside this repo, so these tests always run in CI.

Mirrors `test_labs.py`'s assertion style exactly: malicious labs must
produce a finding whose AST tags are a superset of `expected_finding.ast`
and whose severity is at least `expected_finding.severity_at_least`;
benign labs must produce exactly `expected_findings` (0) — a regression in
either direction (a missed detection, or a new false positive on one of
the benign near-neighbours) fails the suite.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from skillfence.lab_runner import run_lab

CORPUS_ROOT = Path(__file__).resolve().parents[1] / "benchmarks" / "adversarial"

SEVERITY_ORDER = {"low": 0, "medium": 1, "high": 2, "critical": 3}


def _discover_labs() -> list[Path]:
    if not CORPUS_ROOT.is_dir():
        return []
    return sorted(p.parent for p in CORPUS_ROOT.glob("**/ground-truth.yaml"))


_LABS = _discover_labs()

pytestmark = pytest.mark.skipif(
    not _LABS,
    reason=f"benchmarks/adversarial not found at {CORPUS_ROOT} — run "
    "`python3 scripts/build_adversarial_corpus.py` to generate it.",
)


@pytest.mark.parametrize(
    "lab_dir", _LABS or [Path(".")], ids=lambda p: p.relative_to(CORPUS_ROOT).as_posix() if _LABS else "skipped"
)
def test_adversarial_lab_matches_ground_truth(lab_dir: Path):
    gt = yaml.safe_load((lab_dir / "ground-truth.yaml").read_text(encoding="utf-8"))
    result = run_lab(lab_dir, decision="reject", use_policy_store=False)

    if not gt["ground_truth"]["malicious"]:
        assert len(result.findings) == gt.get("expected_findings", 0), (
            f"benign lab {lab_dir.name} produced {len(result.findings)} finding(s) — false positive"
        )
        return

    assert result.findings, f"malicious lab {lab_dir.name} produced no findings — evasion succeeded, false negative"

    expected = gt["expected_finding"]
    top = result.findings[-1]  # the finding tied to the deepest/most-escalated action
    assert set(expected["ast"]).issubset(set(top.ast)), f"expected AST tags {expected['ast']}, got {top.ast}"
    min_severity = SEVERITY_ORDER[expected["severity_at_least"]]
    assert SEVERITY_ORDER[top.severity] >= min_severity, (
        f"expected severity >= {expected['severity_at_least']}, got {top.severity}"
    )


def test_corpus_has_both_malicious_and_benign_labs():
    """Guards against the corpus silently losing its benign controls --
    scaling malicious coverage without keeping benign near-neighbours is
    exactly the "detects everything, proves nothing" trap this corpus
    exists to avoid.
    """
    if not _LABS:
        pytest.skip("corpus not generated")
    malicious = benign = 0
    for lab_dir in _LABS:
        gt = yaml.safe_load((lab_dir / "ground-truth.yaml").read_text(encoding="utf-8"))
        if gt["ground_truth"]["malicious"]:
            malicious += 1
        else:
            benign += 1
    assert malicious >= 10
    assert benign >= 5
